# Generated by Django 4.0.3 on 2022-03-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYC_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
                ('status', models.DateField(max_length=20)),
                ('pan', models.CharField(max_length=20, unique=True)),
                ('aadhar', models.IntegerField(unique=True)),
                ('permanent_address', models.TextField(max_length=500)),
                ('communication_address', models.TextField(max_length=500)),
                ('contact_no', models.IntegerField()),
                ('email_ad', models.CharField(max_length=40, unique=True)),
                ('gross_annual_income', models.CharField(max_length=15)),
                ('occupation', models.CharField(max_length=20)),
                ('applicable_type', models.CharField(max_length=60)),
                ('KYC_check', models.TextField()),
                ('experience', models.TextField()),
                ('goals', models.TextField()),
                ('risk', models.CharField(max_length=20)),
                ('objective', models.TextField()),
            ],
            options={
                'db_table': 'kyc_data',
            },
        ),
    ]
