# Generated by Django 4.0.3 on 2022-03-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_alter_kyc_data_experience_alter_kyc_data_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_data',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
