# Generated by Django 4.0.3 on 2022-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_alter_kyc_data_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_data',
            name='risk',
            field=models.CharField(max_length=200),
        ),
    ]
