# Generated by Django 4.0.3 on 2022-04-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_alter_kyc_data_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='kyc_url_db',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('uiid', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'kyc_url_db',
            },
        ),
    ]
