# Generated by Django 4.0.3 on 2022-04-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_kyc_url_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_url_db',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
