# Generated by Django 4.0.3 on 2022-06-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0008_alter_kyc_url_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_url_db',
            name='used_by',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
