# Generated by Django 4.0.3 on 2022-06-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0009_kyc_url_db_used_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_url_db',
            name='used_by',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
